version : 3.8

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: learnphp-fileimport-transacations
    restart: always
    working_dir: /var/www
    volumes :
      - ../src:/var/www

  ngnix:
    image: nginx:1.27.3-alpine