version : "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: MyApp-SourceCode
    restart: always
    working_dir: /var/www
    volumes :
      - ../src:/var/www

  ngnix:
    image: nginx:1.27.3-alpine
    container_name: nginx-server
    restart: always
    ports: 
      - "8008:80"
    volumes: 
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

